management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: user
  data:
  datasource:
    url: jdbc:mysql://localhost:3307/embarkx
    username: embarkx
    password: embarkx
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8089/eureka/
    register-with-eureka: true
    fetch-registry: true

