management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: product
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: embarkx
    password: embarkx
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
server:
  port: 8083
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8089/eureka/
    register-with-eureka: true
    fetch-registry: true
